### ISSUE TITLE
为什么随便输入Captcha::check结果都是true呢

### ISSUE THREAD

**Issue by KirosHan** [vicens/captcha#1]
$image = Captcha::width(100)->height(40)->make();
将$image->getBase64()字串传到前端显示图片
后台接收input并验证   无论输什么  Captcha::check返回结果都是true？

**Comment by simonetoo** [comment]
是否开启了调试模式呢？如果开启了调试模式，将不会验证输入的正确性。
默认情况下，验证码的调试模式是跟随app.debug，可以通过修改配置文件，关闭验证码调试模式： captcha.debug=false。
